### ISSUE TITLE
Add more log info on unexpected class

### ISSUE THREAD

**Issue by pedrorijo91** [feedzai/feedzai-openml-python#16]
We could show the list of possible values so that data-scientist can better understand the problem. Case sensitiveness is a common headache on this kind of situation.

Is there any information security problem on print the possible values?

https://github.com/feedzai/feedzai-openml-python/blob/fd19dc00b4c25550302a4aa6d02972b3460c3b53/openml-python-common/src/main/java/com/feedzai/openml/python/ClassificationPythonModel.java#L184

**Comment by nmldiegues** [comment]
I don't see a problem with it @pedrorijo91
