### ISSUE TITLE
Improve OpenML docker image for scikit xgboost

### ISSUE THREAD

**Issue by nmldiegues** [feedzai/feedzai-openml-python#20]
The OpenML docker image in https://hub.docker.com/r/feedzai/oracle-jep-miniconda/ must be updated to also install xgboost dependencies for it to work in scikit.

This tutorial can be used to solve the problem: https://machinelearningmastery.com/develop-first-xgboost-model-python-scikit-learn/

After that, we should add a regression test for https://github.com/feedzai/feedzai-openml-python/issues/18 as suggested in https://github.com/feedzai/feedzai-openml-python/pull/19 that uses the model of https://files.feedzai.com/index.php/s/rKbif8CFpee79Gd

**Comment by pedrorijo91** [comment]
we can also add to the documentation that some models may require extra steps besides those we describe

**Comment by nmldiegues** [comment]
Docker image updated (https://hub.docker.com/r/feedzai/oracle-jep-miniconda/builds/betxrq2rmvc6utdvlmahrwm/) via PR (https://github.com/feedzai/oracle-jep-miniconda/pull/3)
