### ISSUE TITLE
Loading a tensor flow model twice fails

### ISSUE THREAD

**Issue by nmldiegues** [feedzai/feedzai-openml-python#26]
The following branch contains a minimal working example that shows that loading any 2 (even if different) tensor flows in the same JVM fail: `reload-tensorflow-same-jvm`

The HEAD commit of that branches has all the necessary contents for reproducibility:

commit 39cff2f96be2ef9dcce6808dea0c943fa5188016
Author: Nuno Diegues <nuno.diegues@feedzai.com>
Date:   Wed Dec 5 15:40:48 2018 +0000

    Minimal working example to show problem when reloading a tensorflow model in the same JVM
    
    The problem seems to be related with tensorflow "reloading"
    of some of its dependents package (seems to be protobuffers2)
    failing.
    
    This seems to be an analogous problem to:
    https://github.com/protocolbuffers/protobuf/issues/3276
    
    To reproduce:
    
    1. Set up a conda env with the following packages
    
    name: my-env-pip
    channels:
      - defaults
    dependencies:
      - ca-certificates=2018.03.07=0
      - certifi=2018.1.18=py36_0
      - libedit=3.1=heed3624_0
      - libffi=3.2.1=hd88cf55_4
      - libgcc-ng=7.2.0=hdf63c60_3
      - libstdcxx-ng=7.2.0=hdf63c60_3
      - ncurses=6.0=h9df7e31_2
      - openssl=1.0.2o=h20670df_0
      - pip=9.0.3=py36_0
      - python=3.6.5=hc3d631a_0
      - readline=7.0=ha6073c6_4
      - setuptools=39.0.1=py36_0
      - sqlite=3.22.0=h1bed415_0
      - tk=8.6.7=hc745277_3
      - wheel=0.31.0=py36_0
      - xz=5.2.3=h55aa19d_2
      - zlib=1.2.11=ha838bed_2
      - pip:
        - absl-py==0.6.1
        - astor==0.7.1
        - cycler==0.10.0
        - gast==0.2.0
        - grpcio==1.16.1
        - jep==3.7.1
        - kiwisolver==1.0.1
        - markdown==3.0.1
        - matplotlib==2.2.2
        - numpy==1.14.2
        - protobuf==3.6.1
        - pyparsing==2.2.0
        - python-dateutil==2.7.3
        - pytz==2018.5
        - scikit-learn==0.19.1
        - scipy==1.0.1
        - six==1.11.0
        - tensorboard==1.10.0
        - tensorflow==1.10.1
        - termcolor==1.1.0
        - werkzeug==0.14.1
        - xgboost==0.72.1
    prefix: /home/nuno.diegues/miniconda2/envs/my-env-pip
    
    2. Compile the project with `mvn clean install -DskipTests`
    
    3. Activate the conda env for JEP to work with:
     * source activate my-env-pip
     * export LD_LIBRARY_PATH=/home/nuno.diegues/miniconda2/envs/my-env-pip/lib/python3.6/site-packages/jep:$LD_LIBRARY_PATH
     * export PATH=/home/nuno.diegues/miniconda2/envs/my-env-pip/bin:$PATH
     * export LD_PRELOAD=/home/nuno.diegues/miniconda2/envs/my-env-pip/lib/libpython3.6m.so
     * naturally, the paths above need to be edited to match your local pc
    
    4. Run the test with:
     * cd openml-generic-python
     * `mvn test -Dtest=TensorflowReloadModelTest`
     * it should fail
    
    5. Change the test to have only 1 model load and confirm that it passes

**Comment by paulojrp** [comment]
issue fixed on #27.
this problem will be fixed in the newest version of the provider (0.1.5). That should be available within a few hours.
